# Nhật Ký Làm Việc

In [1]:
%load_ext autoreload
%autoreload 2

## Bài 1: Tạo Tensor cơ bản
*Tạo một Tensor số nguyên kích thước 2 × 3 và hiển thị kết quả.* <br>
**Yêu cầu:** 
+ Cho biết kích thước, số chiều và kiểu dữ liệu của Tensor a.

In [2]:
%run Bai1.py

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

Kích thước: torch.Size([2, 3])
Số chiều: 2
Kiểu dữ liệu: torch.int32
Kích thước: 2 hàng, 3 cột, số chiều: 2, kiểu dữ liệu: int32


## Bài 2: Tạo các Tensor thường dùng
*Thực hành tạo Tensor ngẫu nhiên, Tensor toàn số 0, toàn số 1 và ma trận đơn vị.* <br>
**Yêu cầu:**
+ Nhận xét sự khác nhau giữa torch.rand() và torch.randn().
+ Tạo thêm một Tensor 5 × 5 chứa toàn giá trị 10.

In [3]:
%run Bai2.py

tensor([[0.1078, 0.8492, 0.1167, 0.0724],
        [0.7292, 0.4517, 0.4562, 0.8486],
        [0.9269, 0.5857, 0.5885, 0.0211]])
tensor([[-0.6287, -0.7575, -0.0839, -0.2942],
        [-0.8187,  0.5710,  0.4362, -1.5735],
        [ 1.2686,  1.0512,  0.4579, -0.6808]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Đánh Giá tourch.rand() và tourch.randn(): 
tourch.rand() tạo ra các số thực ngẫu nhiên Phân phối đều (Uniform) trong khoảng [0;1)
tourch.randn() tạo ra các số thực ngẫu nhiên Phân phối chuẩn (Normal) trong khoảng (-oo;+oo)

Tensor 5x5 chứa toàn giá trị 10:
 tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])


### **Đánh Giá:** 
+ tourch.rand() tạo ra các số thực ngẫu nhiên Phân phối đều (Uniform) trong khoảng [0;1)
+ tourch.randn() tạo ra các số thực ngẫu nhiên Phân phối chuẩn (Normal) trong khoảng (-oo;+oo)

## Bài 3: Kiểm tra thông tin Tensor
*Sử dụng shape, size(), ndim và dtype để kiểm tra các thuộc tính của Tensor.* <br>
**Yêu cầu:** 
+ Giải thích ý nghĩa của torch.Size([2, 3, 4]).

In [4]:
%run Bai3.py

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32
Ý nghĩa của của torch.Size([2, 3, 4]) là tạo 2 ma trận, mỗi ma trận có 3 hàng và 4 cột.


### **Ý Nghĩa:**
+ Ý nghĩa của của torch.Size([2, 3, 4]) là tạo 2 ma trận, mỗi ma trận có 3 hàng và 4 cột.

## Bài 4: Slicing và Indexing
*Truy xuất một phần dữ liệu từ Tensor nhiều chiều.*<br>
**Yêu cầu:**
+ Cho biết shape của a[1] và a[1:, 2:4].
+ Thử lấy hai phần tử cuối cùng trên chiều thứ ba.

In [5]:
%run Bai4.py

Original tensor:
tensor([[[ 0.1226, -0.1520, -0.5496,  0.4146, -1.1200],
         [-0.7722,  1.6721, -0.8897, -0.9655, -0.6745],
         [ 0.5145, -1.1219, -0.2836,  1.4558, -0.2286],
         [-1.3069,  0.3500, -1.3665,  0.6080,  0.7650]],

        [[-0.4389, -0.2267, -1.0228, -0.2733,  0.4344],
         [ 1.1432,  0.5551, -0.4397, -0.1693, -0.5610],
         [ 1.2427,  1.5960, -0.1414, -1.4161, -0.0087],
         [ 0.4998, -0.5303, -1.1680,  0.2539, -0.7075]],

        [[-0.6493, -1.8463, -0.0198, -2.3213, -0.1709],
         [-1.4813, -1.2276, -2.4568,  0.0158,  0.4046],
         [-1.4722,  1.5582, -0.5244, -0.0808, -0.6555],
         [ 1.4102, -1.1211, -0.2043,  0.5840, -0.2449]]])

Tensor a[1]:
tensor([[-0.4389, -0.2267, -1.0228, -0.2733,  0.4344],
        [ 1.1432,  0.5551, -0.4397, -0.1693, -0.5610],
        [ 1.2427,  1.5960, -0.1414, -1.4161, -0.0087],
        [ 0.4998, -0.5303, -1.1680,  0.2539, -0.7075]])

Tensor a[1:, 2:4]:
tensor([[[ 1.2427,  1.5960, -0.1414, -1.4161, -0.0

## Bài 5: Reshape và Flatten
*Thay đổi hình dạng Tensor mà không làm thay đổi số phần tử.* <br>
**Yêu cầu:**
+ Kiểm tra số phần tử trước và sau khi reshape.
+ Thử reshape Tensor thành kích thước 2 × 6.

In [6]:
%run Bai5.py

Original:
tensor([[ 0.0935,  0.6550,  0.6628, -0.2253],
        [-1.3770,  1.2431, -0.1259,  0.4151],
        [-0.1825,  0.2129, -0.9163,  0.3438]])

Flatten:
tensor([ 0.0935,  0.6550,  0.6628, -0.2253, -1.3770,  1.2431, -0.1259,  0.4151,
        -0.1825,  0.2129, -0.9163,  0.3438])

Reshape to 3 x 2 x 2:
tensor([[[ 0.0935,  0.6550],
         [ 0.6628, -0.2253]],

        [[-1.3770,  1.2431],
         [-0.1259,  0.4151]],

        [[-0.1825,  0.2129],
         [-0.9163,  0.3438]]])
Số phần tử ban đầu (3x4): 12
Số phần tử sau khi reshape (3x2x2): 12
Reshape to 2 x 6:
 tensor([[ 0.0935,  0.6550,  0.6628, -0.2253, -1.3770,  1.2431],
        [-0.1259,  0.4151, -0.1825,  0.2129, -0.9163,  0.3438]])
Shape của b: torch.Size([2, 6])


## Bài 6: Phép toán và nhân ma trận
*Thực hiện các phép toán phần tử và phép nhân ma trận bằng toán tử @.* <br>
**Yêu cầu:**
+ Phân biệt phép toán a * b với a @ b.T.
+ Cho biết shape của kết quả a @ b.T.

In [7]:
%run Bai6.py

a: tensor([[-0.2427,  0.5983, -0.2024],
        [-0.0223, -0.0634,  1.4168]])

b: tensor([[ 0.3125,  1.2117, -1.1702],
        [ 0.4667,  0.3448,  1.8020]])

a + b: tensor([[ 0.0699,  1.8100, -1.3726],
        [ 0.4445,  0.2814,  3.2188]])

a / b: tensor([[-0.7765,  0.4937,  0.1729],
        [-0.0477, -0.1838,  0.7862]])

a^2: tensor([[5.8897e-02, 3.5793e-01, 4.0957e-02],
        [4.9637e-04, 4.0173e-03, 2.0072e+00]])

Matrix multiplication: tensor([[ 0.8859, -0.2717],
        [-1.7416,  2.5208]])

======Phân biệt phép toán a * b với a @ b.T===============
a * b: Là phép nhân từng phần tử tương ứng. Yêu cầu a và b phải cùng shape (2, 3). Kết quả trả về có shape (2, 3).
a: tensor([[-0.2427,  0.5983, -0.2024],
        [-0.0223, -0.0634,  1.4168]])

b: tensor([[ 0.3125,  1.2117, -1.1702],
        [ 0.4667,  0.3448,  1.8020]])

Chi tiết:

Vị trí [1,1]: -0.24 * 0.31 = -0.08
Vị trí [1,2]: 0.60 * 1.21 = 0.72
Vị trí [1,3]: -0.20 * -1.17 = 0.24
Vị trí [2,1]: -0.02 * 0.47 = -0.01
Vị trí [2,2]: -

### **Phân Biệt:**
+ a * b: Là phép nhân từng phần tử tương ứng. Yêu cầu a và b phải cùng shape (2, 3). Kết quả trả về có shape (2, 3).
+ a @ b.T: Là phép nhân ma trận. Yêu cầu số cột của a phải bằng số hàng của b.T. Kết quả trả về có shape (2, 2).

## Bài 7: Các hàm thống kê trên Tensor
*Tính trung bình, độ lệch chuẩn và tổng tích lũy theo từng cột.* <br>
**Yêu cầu:**
+ Thay dim=0 bằng dim=1 và nhận xét sự khác nhau.

In [8]:
%run Bai7.py

tensor([[-0.7456,  0.0026, -0.8962,  1.3836],
        [-1.5675,  0.7401, -1.0057, -0.4014],
        [-0.9127,  0.1580,  2.1565, -0.0184]])

Các phép toán thống kê theo chiều:  cột (dim =  0 ):

Mean:
tensor([-1.0752,  0.3002,  0.0849,  0.3213])

Standard deviation:
tensor([0.4344, 0.3888, 1.7949, 0.9397])

Cumulative sum:
tensor([[-7.4559e-01,  2.6032e-03, -8.9619e-01,  1.3836e+00],
        [-2.3131e+00,  7.4275e-01, -1.9019e+00,  9.8223e-01],
        [-3.2257e+00,  9.0073e-01,  2.5461e-01,  9.6383e-01]])



Các phép toán thống kê theo chiều:  hàng (dim =  1 ):

Mean:
tensor([-0.0639, -0.5586,  0.3459])

Standard deviation:
tensor([1.0420, 0.9881, 1.2949])

Cumulative sum:
tensor([[-0.7456, -0.7430, -1.6392, -0.2556],
        [-1.5675, -0.8273, -1.8330, -2.2344],
        [-0.9127, -0.7547,  1.4019,  1.3834]])



NHẬN XÉT SỰ KHÁC NHAU:
- dim=0 (theo Cột): Gộp các hàng lại. Mean/Std trả về Vector 4 phần tử. Cumsum cộng dồn từ trên xuống dưới.
- dim=1 (theo Hàng): Gộp các cột lại. Mean/St

### **NHẬN XÉT:**
+ dim=0 (theo Cột): Gộp các hàng lại. Mean/Std trả về Vector 4 phần tử. Cumsum cộng dồn từ trên xuống dưới.
+ dim=1 (theo Hàng): Gộp các cột lại. Mean/Std trả về Vector 3 phần tử. Cumsum cộng dồn từ trái sang phải.

## Bài 8: Autograd cơ bản
*Tạo biến có requires_grad=True và dùng backward() để tính đạo hàm tự động.* <br>
**Yêu cầu:**
+ Tính thủ công đạo hàm của y = x² tại x = 3.6 và so sánh với x.grad.
+ Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.

In [9]:
%run Bai8.py


x = tensor(3.6000, requires_grad=True)

y = tensor(12.9600, grad_fn=<MulBackward0>)

x.grad = tensor(7.2000)

Thay y = 3*x**2 + 2*x + 1

x = tensor(3.6000, requires_grad=True)

y = tensor(47.0800, grad_fn=<AddBackward0>)

x.grad = tensor(23.6000)


### **Tính Thủ Công:**
*y=x^2* <br>
*y'=2x* <br>
*y'(3.6)=2 x 3.6 = 7.2* <br>
=> Kết qua của x.grad và đạo hàm thủ công y=x^2, Đúng

## Bài 9: Gradient Descent tìm hệ số đa thức
*Sinh dữ liệu từ đa thức y = x² + 2x + 3, sau đó dùng NAdam và autograd để tìm lại ba hệ số.* <br>
*Thay đa thức trong Bài 9 bằng y = 2x² - 3x + 5; huấn luyện và cho biết các hệ số tìm được. <- Bài 11* <br>
**Yêu cầu:**
+ So sánh ba hệ số học được với [1, 2, 3].
+ Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step().


In [10]:
%run Bai9.py


=================== Bài 9: y = x² + 2x + 3 ===================
Initial coefficients (Hệ số ban đầu):
[-0.08176316  0.06117674  0.47170234]

Learned coefficients:
[1.0000, 2.0000, 3.0000]

--- SO SÁNH HỆ SỐ ---
Hệ số gốc (True):        [1.0000, 2.0000, 3.0000]
Hệ số học được (Learned): [1.0000, 2.0000, 3.0000]
Mức độ sai số tuyệt đối:  [0.0000, 0.0000, 0.0000]

=================== Bài 11: y = 2x² - 3x + 5 ===================
Initial coefficients (Hệ số ban đầu):
[-0.99578387 -0.48294058 -0.77142537]

Learned coefficients:
[2.0000, -3.0000, 5.0000]

--- SO SÁNH HỆ SỐ ---
Hệ số gốc (True):        [2.0000, -3.0000, 5.0000]
Hệ số học được (Learned): [2.0000, -3.0000, 5.0000]
Mức độ sai số tuyệt đối:  [0.0000, 0.0000, 0.0000]


### **So Sánh:**
+ Kết Quả Bằng nhau, Thuật toán đúng với thực tế.
### **Giải Thích:**
+ optimizer.zero_grad(): Xóa gradient cũ tích lũy từ bước lặp trước về 0.
+ mse.backward(): Kích hoạt Backpropagation để tính đạo hàm (gradient) của mse theo w và lưu vào w.grad.
+ optimizer.step(): Dựa vào w.grad, thuật toán NAdam sẽ cập nhật giá trị mới cho w để giảm dần lỗi mse.

## Bài 10 :Giải hệ phương trình bằng Autograd
*Tối thiểu hóa tổng sai số bình phương để tìm A, B, C, D thỏa bốn phương trình.* <br>
**Yêu cầu:**
+ Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.
+ Nhận xét vì sao bài toán có thể có nhiều nghiệm.

In [11]:
%run Bai10.py

A = tensor(4.2413, requires_grad=True)
B = tensor(4.7586, requires_grad=True)
C = tensor(3.7587, requires_grad=True)
D = tensor(2.7587, requires_grad=True)
--- NGHIỆM THU ĐƯỢC TỪ AUTOGRAD ---
A = 4.241296768188477
B = 4.758648872375488
C = 3.758666515350342
D = 2.758655071258545

--- KIỂM TRA THAY VÀO 4 PHƯƠNG TRÌNH ---
1) A + B = 8.999945640563965 (Mục tiêu: 9)
2) C - D = 1.0000114440917969 (Mục tiêu: 1)
3) A + C = 7.999963283538818 (Mục tiêu: 8)
4) B - D = 1.9999938011169434 (Mục tiêu: 2)

--- NHẬN XÉT ---
Hệ phương trình bị phụ thuộc tuyến tính (hạng ma trận rank = 3 < số ẩn = 4).
Phương trình (4) thực chất được rút ra từ (1) + (2) - (3): (A+B) + (C-D) - (A+C) = B - D = 2.
Do đó, hệ chỉ có 3 phương trình độc lập cho 4 ẩn -> Hệ có vô số nghiệm phụ thuộc 1 tham số t (ví dụ D = t).


### **Nhận Xét:**
+ Hệ phương trình bị phụ thuộc tuyến tính (hạng ma trận rank = 3 < số ẩn = 4).
+ Phương trình (4) thực chất được rút ra từ (1) + (2) - (3): (A+B) + (C-D) - (A+C) = B - D = 2.
+ Do đó, hệ chỉ có 3 phương trình độc lập cho 4 ẩn -> Hệ có vô số nghiệm phụ thuộc 1 tham số t (ví dụ D = t).

## Bài 11: Viết chương trình PyTorch để thực hiện các yêu cầu sau:
**Yêu Cầu:**
+ Tạo Tensor X có 24 phần tử và reshape lần lượt thành 4 × 6, 2 × 12 và 2 × 3 × 4.
+ Tạo hai Tensor A, B kích thước 3 × 4; tính A+B, A*B, A/B, trung bình theo cột và độ lệch chuẩn theo cột.
+ Cho y = 2x² + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.
+ Thay đa thức trong Bài 9 bằng y = 2x² - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [12]:
%run Bai11.py


Gốc (24 phần tử):
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

Reshape 4 x 6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Reshape 2 x 12:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Reshape 2 x 3 x 4:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
Tensor A:
 tensor([[-0.3010, -0.2983, -0.9722,  1.0405],
        [ 0.3907, -0.0742,  1.6566,  0.2168],
        [ 1.5746,  0.3350,  1.0384,  0.4838]])

Tensor B:
 tensor([[-0.9739,  1.8111,  0.1085, -1.3960],
        [-0.0941, -0.2809,  0.0660,  0.5215],
        [ 1.5900,  1.5056, -1.9250,  0.9996]])

A + B = 
 tensor([[-1.2749,  1.5128, -0.8637, -0.3555],
        [ 0.2966, -0.3551,  1.722

In [13]:
!jupyter nbconvert --to html lab01.ipynb

[NbConvertApp] Converting notebook lab01.ipynb to html
[NbConvertApp] Writing 315312 bytes to lab01.html
